version: "3.3"

services:

  app:
    build: .
    command: gunicorn --bind 0.0.0.0:5000 main:app
    container_name: "app-service"
    env_file: .env
    volumes:
      - ".:/usr/src/app"
    ports:
      - "5000"
    depends_on:
      - db
    links:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`app.localhost`)"
      - "traefik.http.routers.app.entrypoints=web"

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: financial_viewer

  traefik:
    image: "traefik:v2.0"
    container_name: "traefik-service"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
